### ISSUE TITLE
Pinocchio Mac Import Error: (libboost_python38-mt.dylib)

### ISSUE THREAD

**Issue by AtharvaSune** [stack-of-tasks/pinocchio#1250]
```
Python 3.7.5 (v3.7.5:5c02a39a0b, Oct 14 2019, 18:49:57) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/pinocchio/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .libpinocchio_pywrap import *
ImportError: dlopen(/usr/local/opt/pinocchio/lib/python3.8/site-packages/pinocchio/libpinocchio_pywrap.so, 2): Symbol not found: __Py_tracemalloc_config
  Referenced from: /usr/local/opt/boost-python3/lib/libboost_python38-mt.dylib
  Expected in: flat namespace
 in /usr/local/opt/boost-python3/lib/libboost_python38-mt.dylib
```
Using MacOS Catalina, python 3.7.5

These are my env variables
```
export PYTHONPATH="/usr/local/opt/pinocchio/lib/python3.8/site-packages:$PYTHONPATH"
export LD_LIBRARY_PATH="/usr/local/opt/pinocchio/lib/:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH=/usr/local/opt/pinocchio/lib/pkgconfig:$PKG_CONFIG_PATH
```

**Comment by jcarpent** [comment]
You should use python3.8, on OS X, we made the choice of python3.8.

**Comment by jcarpent** [comment]
If you want, you can use Conda to get the 3.7 version of the lib.

**Comment by jcarpent** [comment]
@AtharvaSune I think this issue is solved. Please reopen it if needed.
