### ISSUE TITLE
[PyPI] libboost not found with pin==2.6.14

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1862]
The CI from [robot_descriptions.py](https://github.com/robot-descriptions/robot_descriptions.py/actions/runs/4115761899/jobs/7104912177) has started breaking. Its last job installed ``pin==2.6.14``:

```
loader-pinocchio: freeze> python -m pip freeze --all
loader-pinocchio: attrs==22.2.0,cmeel==0.31.0,cmeel-assimp==5.2.5,cmeel-boost==1.81.0,cmeel-console-bridge==1.0.2.1,cmeel-octomap==1.9.8.1,cmeel-tinyxml==2.6.2.1,cmeel-urdfdom==3.1.0.1,eigenpy==2.9.2,exceptiongroup==1.1.0,gitdb==4.0.10,GitPython==3.1.30,hpp-fcl==2.2.0,iniconfig==2.0.0,numpy==1.24.2,packaging==23.0,pin==2.6.14,pip==23.0,pluggy==1.0.0,pytest==7.2.1,robot_descriptions @ file:///home/runner/work/robot_descriptions.py/robot_descriptions.py/.tox/.tmp/package/1/robot_descriptions-1.4.0rc0.tar.gz,setuptools==67.1.0,smmap==5.0.0,tomli==2.0.1,tqdm==4.64.1,wheel==0.38.4
tox: loader-pinocchio
  loader-pinocchio: commands[0]> pytest --import-mode=importlib tests/loaders/test_pinocchio.py
  ============================= test session starts ==============================
  platform linux -- Python 3.8.16, pytest-7.2.1, pluggy-1.0.0
  cachedir: .tox/loader-pinocchio/.pytest_cache
  rootdir: /home/runner/work/robot_descriptions.py/robot_descriptions.py
  collected 0 items / 1 error
  
  ==================================== ERRORS ====================================
  _______________ ERROR collecting tests/loaders/test_pinocchio.py _______________
  ImportError while importing test module '/home/runner/work/robot_descriptions.py/robot_descriptions.py/tests/loaders/test_pinocchio.py'.
  Hint: make sure your test modules/packages have valid Python names.
  Traceback:
  tests/loaders/test_pinocchio.py:22: in <module>
      from robot_descriptions.loaders.pinocchio import load_robot_description
  .tox/loader-pinocchio/lib/python3.8/site-packages/robot_descriptions/loaders/pinocchio.py:26: in <module>
      import pinocchio as pin
  .tox/loader-pinocchio/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py:6: in <module>
      from .pinocchio_pywrap import *
  E   ImportError: libboost_python38.so.1.80.0: cannot open shared object file: No such file or directory
```

I can also reproduce the issue locally in a clean environment (here Python 3.9):

```console
$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nelson/.micromamba/envs/pin-pypi-test/lib/python3.9/site-packages/cmeel.prefix/lib/python3.9/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: libboost_python39.so.1.80.0: cannot open shared object file: No such file or directory
```

@nim65s Do you have an insight as to what is causing this?

**Comment by stephane-caron** [comment]
Looks like a duplicate of https://github.com/stack-of-tasks/pinocchio/issues/1844, somehow the fix did not propagate?

**Comment by stephane-caron** [comment]
Yeah, this is clearly the same issue. Closing as a duplicate, heading to https://github.com/stack-of-tasks/pinocchio/issues/1844.
