### ISSUE TITLE
PyPI installation: undefined symbol: _ZN7eigenpy9NumpyType7getTypeEv

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/pinocchio#1937]
Importing Pinocchio has started to fail in the CI of Pink today:

```
ImportError: /home/runner/work/pink/pink/.tox/coverage/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/pinocchio_pywrap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7eigenpy9NumpyType7getTypeEv
```

I just checked in a virtualenv and the issue happens on my machine as well:

```console
$ virtualenv test
$ source test/bin/activate
$ pip install pin
... (see below)
$ python
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pinocchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nelson/kron/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/__init__.py", line 6, in <module>
    from .pinocchio_pywrap import *
ImportError: /home/nelson/kron/lib/python3.8/site-packages/cmeel.prefix/lib/python3.8/site-packages/pinocchio/pinocchio_pywrap.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN7eigenpy9NumpyType7getTypeEv
```

Pip install log:

```
Collecting pin
  Using cached pin-2.6.17-0-cp38-cp38-manylinux_2_17_x86_64.whl (6.1 MB)
Collecting cmeel-tinyxml
  Using cached cmeel_tinyxml-2.6.2.1-2-cp38-cp38-manylinux_2_17_x86_64.whl (88 kB)
Collecting cmeel-urdfdom
  Using cached cmeel_urdfdom-3.1.0.1-2-cp38-cp38-manylinux_2_17_x86_64.whl (433 kB)
Collecting hpp-fcl
  Using cached hpp_fcl-2.3.1-0-cp38-cp38-manylinux_2_17_x86_64.whl (2.3 MB)
Collecting cmeel-console-bridge
  Using cached cmeel_console_bridge-1.0.2.1-2-cp38-cp38-manylinux_2_17_x86_64.whl (24 kB)
Collecting cmeel
  Downloading cmeel-0.39.0-py3-none-any.whl (12 kB)
Collecting tomli<3.0.0,>=2.0.1
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting cmeel-assimp
  Using cached cmeel_assimp-5.2.5-4-cp38-cp38-manylinux_2_17_x86_64.whl (13.5 MB)
Collecting eigenpy
  Downloading eigenpy-3.0.0-3-cp38-cp38-manylinux_2_17_x86_64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 1.6 MB/s eta 0:00:00
Collecting cmeel-octomap
  Using cached cmeel_octomap-1.9.8.1-2-cp38-cp38-manylinux_2_17_x86_64.whl (699 kB)
Collecting cmeel-boost
  Downloading cmeel_boost-1.81.0-12-cp38-cp38-manylinux_2_17_x86_64.whl (34.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.8/34.8 MB 2.8 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 1.5 MB/s eta 0:00:00
Installing collected packages: tomli, numpy, cmeel, cmeel-urdfdom, cmeel-tinyxml, cmeel-octomap, cmeel-console-bridge, cmeel-boost, cmeel-assimp, eigenpy, hpp-fcl, pin
Successfully installed cmeel-0.39.0 cmeel-assimp-5.2.5 cmeel-boost-1.81.0 cmeel-console-bridge-1.0.2.1 cmeel-octomap-1.9.8.1 cmeel-tinyxml-2.6.2.1 cmeel-urdfdom-3.1.0.1 eigenpy-3.0.0 hpp-fcl-2.3.1 numpy-1.24.3 pin-2.6.17 tomli-2.0.1
```

**Comment by fabinsch** [comment]
A new version of `eigenpy==3.0.0` [has been released](https://github.com/stack-of-tasks/eigenpy/releases/tag/v3.0.0), which seems to not be compatible with `pinocchio==pin-2.6.17`. For now you have to downgrade to `eigenpy==2.9.2`. Adding the line
```
RUN pip install eigenpy==2.9.2
```
to your dockerfile @JonathanKuelz makes it work again.

The issue has been fixed in conda: https://github.com/stack-of-tasks/pinocchio/issues/1935 by pinning the correct version. @nim65s can you help us for pypi ?

**Comment by nim65s** [comment]
Thanks for the report. The workaround is the correct on. I'll fix this, but this will require some time to rebuild.

**Comment by stephane-caron** [comment]
Import is now successful :+1: but following up we run into https://github.com/stack-of-tasks/pinocchio/issues/1940
