### ISSUE TITLE
Error while running the rviz-viewer.py

### ISSUE THREAD

**Issue by ajxdhe** [stack-of-tasks/pinocchio#2136]
When I runned the rviz-viewer.py,an issue was encountered.
`/home/skywalker/anaconda3/envs/pino/bin/python /home/skywalker/pinocchio/examples/rviz-viewer.py
Traceback (most recent call last):
  File "/home/skywalker/pinocchio/examples/rviz-viewer.py", line 22, in <module>
    viz.initViewer()
  File "/home/skywalker/anaconda3/envs/pino/lib/python3.8/site-packages/pinocchio/visualize/rviz_visualizer.py", line 63, in initViewer
    from rviz import bindings as rviz
  File "/opt/ros/noetic/lib/python3/dist-packages/rviz/__init__.py", line 25, in <module>
    from . import librviz_sip as bindings
ValueError: PyCapsule_GetPointer called with incorrect name`

**Comment by jcarpent** [comment]
It seems the issue is coming from RVIZ and PyQT (see https://answers.ros.org/question/371691/valueerror-pycapsule_getpointer-called-with-incorrect-name/).
