### ISSUE TITLE
Use the pinocchio.casadi module inside an existing docker container

### ISSUE THREAD

**Issue by FrancescoD98** [stack-of-tasks/pinocchio#2394]
Hi, first of all thank you for your amazing work.

I'm currently working on a project on ROS noetic inside an existing docker container using python.
I would like to use the new casadi support of pinocchio 3, however I've tried to install the latest version using (1) the [installation guide](https://stack-of-tasks.github.io/pinocchio/download.html), (2) building it from source and (3) using conda.

 - With the first method python doesn't find the module `pinocchio.casadi`. The installation procedure was to copy-paste exactly the command on the download page.
 - When building from source, the error is
```
>>> import pinocchio.casadi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/openrobots/lib/python3.8/site-packages/pinocchio/casadi/__init__.py", line 11, in <module>
    from ..pinocchio_pywrap_casadi import *
ImportError: libcasadi.so.3.7: cannot open shared object file: No such file or directory
```
`pinocchio` was built with the options `-DCMAKE_INSTALL_PREFIX=/opt/openrobots` and `-DBUILD_WITH_CASADI_SUPPORT=ON ` 
 - finally the installation with `conda` works outside the container

Is there anything I'm missing? Could you please provide instructions on how to install everything as it should be?

Thanks in advance for your kind reply.

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
