### ISSUE TITLE
Error getting to run an example

### ISSUE THREAD

**Issue by emrecemal** [stack-of-tasks/pinocchio#2451]
Hello,

I freshly created a conda environment, and install pinocchio, and I wanted to run this example: examples/cassie-simulation.py
However, I'm getting this error:

```
Traceback (most recent call last):
  File "/home/emrecemal/git_ws/check_cassie/main.py", line 30, in <module>
    robot = pinocchio.RobotWrapper.BuildFromSDF(
  File "/home/emrecemal/git_ws/check_cassie/.venv/lib/python3.10/site-packages/pinocchio/robot_wrapper.py", line 53, in BuildFromSDF
    robot.initFromSDF(
  File "/home/emrecemal/git_ws/check_cassie/.venv/lib/python3.10/site-packages/pinocchio/robot_wrapper.py", line 74, in initFromSDF
    model, constraint_models, collision_model, visual_model = buildModelsFromSdf(
  File "/home/emrecemal/git_ws/check_cassie/.venv/lib/python3.10/site-packages/pinocchio/shortcuts.py", line 113, in buildModelsFromSdf
    model, constraint_models = pin.buildModelFromSdf(
AttributeError: module 'pinocchio.pinocchio_pywrap_default' has no attribute 'buildModelFromSdf'. Did you mean: 'buildModelFromUrdf'?
```

How can I solve it?

**Comment by MegMll** [comment]
Hello, 

If you want Sdf support, you need to compile pinocchio from source, because it's not included in the conda package.

**Comment by jorisv** [comment]
Hello @emrecemal,

Since Pinocchio 3.3.0, the conda package is build with SDF support.
